### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by igouss** [eulerto/wal2json#80] opened 2018-09-11 15:01 UTC
I've received the following data
```
{
  "xid": 121842061,
  "nextlsn": "A79/18160B98",
  "timestamp": "2000-01-01 00:00:00+00",
  "change": [
    {
      "kind": "delete",
      "schema": "public",
      "table": "foo",
      "oldkeys": {
        "keynames": [
          "foo_id"
        ],
        "keyvalues": [
          1234
        ]
      }
    }
  ]
}
```
timestamp looks suspiciously like a null timestamptz (https://www.npgsql.org/dev/types.html).

**Comment by eulerto** [comment] 2018-09-11 17:48
@igouss You don't provide enough information. Postgres version? Replication tool (native, JDBC, psycopg2, etc)? I bet it should be related to replication origin configuration.

**Comment by igouss** [comment] 2018-09-11 18:01
* PostgreSQL 10.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit
* JDBC postgresql driver, version 42.2.5
* WAL2JSON git d4c0e81

**Comment by eulerto** [comment] 2018-09-11 18:10
Could you provide a test case?

**Comment by igouss** [comment] 2018-09-11 18:43
I'll try, I'm investigating it.

**Comment by igouss** [comment] 2018-09-11 21:48
1) Unable to reproduce it locally so far
2) ```{"xid":94087451,"nextlsn":"78E/A406D838","timestamp":"2000-01-01 00:00:00+00","change":[]}``` I see a lot in empty change-sets.

**Comment by eulerto** [comment] 2018-09-11 21:49
@igouss empty change means DDL.

**Comment by alexshakurin** [comment] 2018-09-12 08:10
I also have this issue and it's related to origin configuration. For me issue occurs when I use `pg_replication_origin_session_setup` without `pg_replication_origin_xact_setup`. Here's how I can reproduce the issue using pgAdmin:
1) Open two tabs to the same database
2) Execute the following SQL line by line in the first tab:
```
begin
select * from pg_replication_origin_session_setup('server') -- put actual replication origin name here
insert into translations (translationid) values (149999999) -- insert into any other table in database
commit
```
3) In the second tab run the following sql:
`select * from pg_logical_slot_peek_changes('<sync slot name>', null, null, 'include-timestamp', 'on')`
4) In the first tab run the following sql:
`select * from pg_replication_origin_session_reset()`
and repeat step no. 2
5) After that all timestamps are empty

Anyway, issue is not related to wal2json as this value is coming from PG WAL.

**Comment by eulerto** [comment] 2019-03-25 23:41
Since I didn't receive a test case from @igouss I bet this is related to replication origin setup like @alexshakurin showed above. I close this issue but feel free to reopen it if you have a test case.

**Closed by eulerto** 2019-03-25 23:41 UTC
Labels: more info

**Comment by enggarranu** [comment] 2020-02-11 08:12
hi @eulerto ,

Im geting a wrong timestamp output. 
The timestamp output from include-timestamp parameter is 2002-12-30 10:46:03.524744+07 and it is static (not changing at all)

I created slot with this command :
`pg_recvlogical -d test-db --slot test_slot --create-slot -P wal2json`

and get output with this command :
`pg_recvlogical -d test-db --slot test_slot --start -o pretty-print=1 -o include-timestamp=true -f -
`
output:
```
{
	"timestamp": "2002-12-30 10:46:03.524744+07",
	"change": [
		{
			"kind": "update",
			"schema": "public",
			"table": "inbox",
			"columnnames": ["inbox_id", "last_reply_by", "last_reply_time", "last_reply_message",  "create_time",  "update_time", "shop_id"],
			"columntypes": ["bigint", "timestamp without time zone", "text", "timestamp without time zone", "timestamp without time zone", "bigint"],
			"columnvalues": [54321, "2019-10-17 19:00:56.43153", "&nbsp;tepung ketan",  "2019-07-17 21:20:33.176885", "2020-02-11 14:50:19.457752", 1234567],
			"oldkeys": {
				"keynames": ["inbox_id"],
				"keytypes": ["bigint"],
				"keyvalues": [54321]
			}
		}
	]
}
```

please help me, how to fix the timestamp on json output.
Thanks in advance.
