### ISSUE TITLE
How to map each committed transaction to wal2json's JSON entries

### ISSUE THREAD

**Issue by gogo9th** [eulerto/wal2json#115] opened 2019-05-07 07:53 UTC
Hi,

I working on a project which requires a PostgreSQL tool that should provide the following 2 functionalites:
1. Record each SQL transaction in the exact order they are committed
2. Map each committed SQL transaction to the JSON record describing changes in tables

I found wal2json to be very useful and helpful for achieving this goal, which I really appreciate. However, I wonder if wal2json could also record each committed SQL transaction, and map each of them to the JSON entry of table changes. Based on your README instruction, it seems that wal2json only outputs changes without information of committed transactions... I would really appreciate your comments and help on this.

**Comment by eulerto** [comment] 2019-05-07 15:43
> I wonder if wal2json could also record each committed SQL transaction, and map each of them to the JSON entry of table changes.

By design, logical replication only passes committed transactions to output plugins so everything wal2json outputs is committed transactions. "change" contains an array of changes. "change" contains transaction data. Each "change" entry is an affected row. README has an example.

> Based on your README instruction, it seems that wal2json only outputs changes without information of committed transactions...

What information do you expect?

**Comment by gogo9th** [comment] 2019-05-07 17:31
For your first example in README, I need to get the following committed queries from logging:
===================================
CREATE TABLE table_with_pk (a SERIAL, b VARCHAR(30), c TIMESTAMP NOT NULL, PRIMARY KEY(a, c));
CREATE TABLE table_without_pk (a SERIAL, b NUMERIC(5,2), c TEXT);

BEGIN;
INSERT INTO table_with_pk (b, c) VALUES('Backup and Restore', now());
INSERT INTO table_with_pk (b, c) VALUES('Tuning', now());
INSERT INTO table_with_pk (b, c) VALUES('Replication', now());
DELETE FROM table_with_pk WHERE a < 3;

INSERT INTO table_without_pk (b, c) VALUES(2.34, 'Tapir');
-- it is not added to stream because there isn't a pk or a replica identity
UPDATE table_without_pk SET c = 'Anta' WHERE c = 'Tapir';
COMMIT;
======================
And I need to know what are the changes caused by each INSERT, DELETE, and UPDATE query above (i.e., the exact mapping between the query and changes).

**Comment by eulerto** [comment] 2019-05-07 17:44
I'm not sure I understand what you want. The exact SQL command is **not** provided to the output plugin (for example, if you have a INSERT ... SELECT, it is just one SQL command that could supply many rows). The output plugin only knows that that transaction has 5 affected rows (2 INSERTs, 2 DELETEs and 1 UPDATE) but it does not know that it was produced by 3 SQL commands (1 INSERT, 1 DELETE and 1 UPDATE).

It seems we have a XY problem here. If you try to explain what you want to achieve, I can say if wal2json is suitable for your needs.

**Comment by gogo9th** [comment] 2019-05-07 17:54
Yes, what you explain is exactly what I want, and as you said the output plugin doesn't contain the INSERTs, DELETES, UPDATE information. Also, the output plugin doesn't contain CREATE TABLE, CREATE TRIGGER, DROP TABLE information. I wonder if these information could be incorporated into wal2json by modifying certain part in the source code (Or are these fundamentally difficult for wal2json to achieve?)

**Comment by eulerto** [comment] 2019-05-07 18:01
By design, logical replication does not provide such information to output plugins. DDL (besides TRUNCATE that is already supported) should be incorporated in a few releases. However, provide the SQL command, it won't. It seems you want a trigger-based replication. IMHO replicate SQL commands have more caveats than replicate data. What would you do with volatile function calls?

**Comment by gogo9th** [comment] 2019-05-07 19:10
Thanks for your comments. In MySQL, there seems to be an option to log all committed queries:
https://stackoverflow.com/questions/303994/log-all-queries-in-mysql

But is it that PostgreSQL doesn't have such committed SQL command logging options?

**Comment by eulerto** [comment] 2019-05-08 03:11
> But is it that PostgreSQL doesn't have such committed SQL command logging options?

You can always log queries in the log file (see `log_min_duration_statement` and `log_statement`).

**Comment by gogo9th** [comment] 2019-05-08 04:49
Thanks, that's really great to know, I found a few good tutorials on using PostgreSQL's `log_statement` feature:

- [https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-query-logging/
﻿-](https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-query-logging/
﻿-) [https://www.endpoint.com/blog/2012/06/30/logstatement-postgres-all-full-logging](https://www.endpoint.com/blog/2012/06/30/logstatement-postgres-all-full-logging)
﻿- [https://stackoverflow.com/questions/722221/how-to-log-postgresql-queries](https://stackoverflow.com/questions/722221/how-to-log-postgresql-queries)

But are you saying that mapping each of your wal2json output block (INSERT, DELETE, UPDAET) to its associated SQL statement logged by `log_statement` is impossible, because wal2json's outputs are generated only based on the WAL file which doesn't log SQL statements and the WAL file is managed independently from the SQL log file managed by `log_statement`?

**Comment by eulerto** [comment] 2019-05-08 19:27
Exact.

**Closed** 2019-05-08 19:28 UTC
Labels: question
